# Excercise #2
# By Monico Luis
# January 15, 2020
# DESCRIPTION: Python print ASCII Program (a shaka hand).

print(" ")
print("")
print("")
print("")
print("")
print(" =")
print("=   =")
print("=   =")
print("=====")
print("=   =")
print("=    =")
print("=    =")
print("======")
print("=      =          ===    ===  ")
print("=      = ==   ==   ===    =")
print("=          =====      ===== =")
print("=          =    =    =    =    ==")
print("=          =    =    =    =     =          == =")
print("=          =    =    =    =     =         ==   =")
print("=          ======    ======     =        =     =")
print("=          =    =    =    =     =       =       =")
print("=          =    =    =    =     =      =        =")
print("=          ======    ======   =       =         =")
print("=                             =     ==         =")
print("=                             ======          =")
print("=                             =              =")
print("=                             =            =")
print("=                             =          =")
print("=                             =        =")
print("=                                ====")
print("=================================")
print("==                           ===")
print(" ==                        ==")
print(" ==                        ==")
print(" ==                        ==")
print(" ==                        ==")
print(" ==                        ==")
print(" ===========================")
